-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 23:50:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mimik
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mimik
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mimik` DEFAULT CHARACTER SET utf8 ;
USE `mimik` ;

-- -----------------------------------------------------
-- Table `mimik`.`corrections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimik`.`corrections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  `timeOfWork` INT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimik`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimik`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NULL,
  `surname` VARCHAR(30) NULL,
  `idCor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_1_idx` (`idCor` ASC) VISIBLE,
  CONSTRAINT `fk_employees_1`
    FOREIGN KEY (`idCor`)
    REFERENCES `mimik`.`corrections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimik`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimik`.`customers` (
  `id` INT NOT NULL,
  `name` VARCHAR(15) NULL,
  `surname` VARCHAR(30) NULL,
  `car` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimik`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimik`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `idCust` INT NULL,
  `idEmp` INT NULL,
  `idCor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_1_idx` (`idCust` ASC) VISIBLE,
  INDEX `fk_orders_2_idx` (`idCor` ASC) VISIBLE,
  INDEX `fk_orders_3_idx` (`idEmp` ASC) VISIBLE,
  CONSTRAINT `fk_orders_1`
    FOREIGN KEY (`idCust`)
    REFERENCES `mimik`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_2`
    FOREIGN KEY (`idCor`)
    REFERENCES `mimik`.`corrections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_3`
    FOREIGN KEY (`idEmp`)
    REFERENCES `mimik`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mimik` ;

-- -----------------------------------------------------
-- Placeholder table for view `mimik`.`empCors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimik`.`empCors` (`name` INT, `surname` INT);

-- -----------------------------------------------------
-- View `mimik`.`empCors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mimik`.`empCors`;
USE `mimik`;
CREATE  OR REPLACE VIEW `empCors` AS SELECT employees.name, employees.surname, corrections.name from employees, corrections where employee.idCor = corrections.id;
USE `mimik`;

DELIMITER $$
USE `mimik`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`orders_AFTER_INSERT` AFTER INSERT ON `orders` FOR EACH ROW
BEGIN
	update orders set orders.date = current_timestamp where date = null;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
